### ISSUE TITLE
Solution to having multiple "Shared" folders

### ISSUE THREAD

**Issue by maxcampb** [seascape-models/seascape_collaboration#46]
I thought of a solution the having multiple "Shared" folders situation. You can add a pattern in the .gitignore that allows you to have a different name for each Shared folder as long as it starts with "Shared" (e.g. Shared_fish_counting). Happy it implement if you like @cbrown5 ?

**Comment by cbrown5** [comment]
Wow, thank for still thinking about this! That's a simple and elegant solution, so it would be great if you can implement that. Hope you are doing well
